<?php

return [
    'brand' => [
        'name' => 'Keep Sydney Live',
        'tagline' => 'Keep Sydney Live.',
        'description' => 'Keep Sydney Live is an independent Sydney guide to live music, events, nightlife, food, culture and everything happening across the city.',
    ],

    /*
     * The map should read as an editorial city map: paper background, charcoal
     * roads, no product-default colouring. CARTO's Positron is the closest
     * key-less raster basemap; attribution is mandatory.
     */
    'map' => [
        'centre' => ['lat' => -33.8688, 'lng' => 151.2093],
        'zoom' => 11,
        'min_zoom' => 9,
        'max_zoom' => 18,
        'tiles' => [
            'day' => 'https://basemaps.cartocdn.com/rastertiles/light_all/{z}/{x}/{y}{r}.png',
            'night' => 'https://basemaps.cartocdn.com/rastertiles/dark_all/{z}/{x}/{y}{r}.png',
        ],
        'attribution' => '&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions" target="_blank" rel="noopener">CARTO</a>',
    ],

    /*
     * Artwork uploaded from the admin. Everything is re-encoded to WebP, so the
     * only knobs are how wide and how lossy.
     */
    'media' => [
        'disk' => env('KSLIVE_MEDIA_DISK', env('FILESYSTEM_DISK', 'public')),
        'directory' => 'media',
        'max_width' => 2000,
        'quality' => 82,
    ],

    /*
     * Hero headlines. One is picked at random per page load, so the homepage
     * has a different opening line each visit. Keep them short, warm and
     * observational: an invitation, never a sales pitch.
     */
    'headlines' => [
        'A good excuse to leave the house.',
        'Tonight, sorted.',
        'Sydney is on. Go and see it.',
        'Better than staying in.',
        'Somewhere to be tonight.',
        'The city is doing something. Join in.',
        'Say yes to a Tuesday.',
        'Worth getting off the couch for.',
        'Make a weeknight count.',
        'Find your next favourite room.',
        'Go outside. It is worth it.',
        'Turn up somewhere new.',
        'Sydney never quite sits still.',
        'Do something you will talk about later.',
        'The good stuff is happening now.',
        'Plans, made easy.',
        'A city worth showing up for.',
        'Live rooms, loud rooms, good people.',
        'Come for the gig, stay for the walk home.',
        'Never a dull Thursday.',
        'Small rooms, big nights.',
        'Put the phone down. Sydney is on.',
        'There is always something on.',
        'Your weekend starts here.',
        'Go and be somewhere.',
        'Sydney after dark, sorted.',
        'Take the long way home.',
        'Something on, every night of the week.',
        'The best nights start with a plan.',
        'Meet someone somewhere good.',
        'Leave the house. Thank us later.',
        'A night out beats a night in.',
        'Sydney, at its most alive.',
        'Good things are happening nearby.',
        'Make it a night to remember.',
    ],

    'categories' => [
        ['slug' => 'music', 'name' => 'Music'],
        ['slug' => 'comedy', 'name' => 'Comedy'],
        ['slug' => 'theatre', 'name' => 'Theatre'],
        ['slug' => 'nightlife', 'name' => 'Nightlife'],
        ['slug' => 'food-drink', 'name' => 'Food & Drink'],
        ['slug' => 'arts', 'name' => 'Arts'],
        ['slug' => 'sport', 'name' => 'Sport'],
        ['slug' => 'festivals', 'name' => 'Festivals'],
    ],

    'neighbourhoods' => [
        'newtown',
        'surry-hills',
        'darlinghurst',
        'pyrmont',
        'sydney-cbd',
        'barangaroo',
        'chippendale',
        'redfern',
        'marrickville',
        'bondi',
        'parramatta',
    ],

    'venues' => [
        [
            'slug' => 'enmore-theatre',
            'name' => 'Enmore Theatre',
            'suburb' => 'Newtown',
            'address' => '118-132 Enmore Road, Newtown NSW 2042',
            'description' => 'A Sydney live institution blending heritage architecture with a relentless music calendar.',
            'website' => 'https://example.com/enmore-theatre',
            'social_url' => 'https://instagram.com',
            'latitude' => -33.9004,
            'longitude' => 151.1736,
            'image' => 'https://images.unsplash.com/photo-1514306191717-452ec28c7814?auto=format&fit=crop&w=1600&q=80',
            'transport' => '10-minute walk from Newtown Station. Multiple bus routes along King Street.',
        ],
        [
            'slug' => 'factory-theatre',
            'name' => 'Factory Theatre',
            'suburb' => 'Marrickville',
            'address' => '105 Victoria Road, Marrickville NSW 2204',
            'description' => 'A mixed-format venue for indie gigs, showcases and left-field community nights.',
            'website' => 'https://example.com/factory-theatre',
            'social_url' => 'https://instagram.com',
            'latitude' => -33.9076,
            'longitude' => 151.1625,
            'image' => 'https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1600&q=80',
            'transport' => 'Short walk from Sydenham Station with late-night ride-share options nearby.',
        ],
        [
            'slug' => 'metro-theatre',
            'name' => 'Metro Theatre',
            'suburb' => 'Sydney CBD',
            'address' => '624 George Street, Sydney NSW 2000',
            'description' => 'An iconic city room where touring acts and big local nights land hard.',
            'website' => 'https://example.com/metro-theatre',
            'social_url' => 'https://instagram.com',
            'latitude' => -33.8770,
            'longitude' => 151.2064,
            'image' => 'https://images.unsplash.com/photo-1562329265-95a6d7a83440?auto=format&fit=crop&w=1600&q=80',
            'transport' => 'Opposite Gadigal Metro and central bus corridors.',
        ],
        [
            'slug' => 'hayes-theatre',
            'name' => 'Hayes Theatre Co',
            'suburb' => 'Potts Point',
            'address' => '19 Greenknowe Avenue, Potts Point NSW 2011',
            'description' => 'Intimate theatre and cabaret programming with a cult Sydney following.',
            'website' => 'https://example.com/hayes-theatre',
            'social_url' => 'https://instagram.com',
            'latitude' => -33.8732,
            'longitude' => 151.2230,
            'image' => 'https://images.unsplash.com/photo-1615414047026-802692414b79?auto=format&fit=crop&w=1600&q=80',
            'transport' => 'Close to Kings Cross Station and Macleay Street bus links.',
        ],
        [
            'slug' => 'carriageworks',
            'name' => 'Carriageworks',
            'suburb' => 'Eveleigh',
            'address' => '245 Wilson Street, Eveleigh NSW 2015',
            'description' => 'Industrial-scale arts, markets and festivals in a striking converted rail yard.',
            'website' => 'https://example.com/carriageworks',
            'social_url' => 'https://instagram.com',
            'latitude' => -33.8953,
            'longitude' => 151.1922,
            'image' => 'https://images.unsplash.com/photo-1578855019520-af8101c056e2?auto=format&fit=crop&w=1600&q=80',
            'transport' => 'Walkable from Redfern Station with cycle access via Wilson Street.',
        ],
    ],

    'events' => [
        [
            'title' => 'Late Set Fridays at Enmore',
            'slug' => 'late-set-fridays-enmore',
            'description' => 'A stacked local lineup, open dance floor and post-show DJs until late.',
            'start_datetime' => '2026-08-14T19:30:00+10:00',
            'end_datetime' => '2026-08-14T23:45:00+10:00',
            'venue_slug' => 'enmore-theatre',
            'suburb' => 'Newtown',
            'category' => 'Music',
            'category_slug' => 'music',
            'image' => 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1600&q=80',
            'price' => '$38',
            'ticket_url' => 'https://example.com/tickets/late-set-fridays-enmore',
            'latitude' => -33.9004,
            'longitude' => 151.1736,
            'featured' => true,
        ],
        [
            'title' => 'Basement Stand-Up Showcase',
            'slug' => 'basement-standup-showcase',
            'description' => 'Sydney comics testing new sets with low ceilings and loud crowds.',
            'start_datetime' => '2026-08-14T20:00:00+10:00',
            'end_datetime' => '2026-08-14T22:00:00+10:00',
            'venue_slug' => 'metro-theatre',
            'suburb' => 'Sydney CBD',
            'category' => 'Comedy',
            'category_slug' => 'comedy',
            'image' => 'https://images.unsplash.com/photo-1580188928585-0ef5c1a5c4dd?auto=format&fit=crop&w=1600&q=80',
            'price' => '$22',
            'ticket_url' => 'https://example.com/tickets/basement-standup-showcase',
            'latitude' => -33.8770,
            'longitude' => 151.2064,
            'featured' => true,
        ],
        [
            'title' => 'After Dark Gallery Circuit',
            'slug' => 'after-dark-gallery-circuit',
            'description' => 'A guided late opening across small galleries with live sound design.',
            'start_datetime' => '2026-08-14T18:30:00+10:00',
            'end_datetime' => '2026-08-14T21:30:00+10:00',
            'venue_slug' => 'carriageworks',
            'suburb' => 'Chippendale',
            'category' => 'Arts',
            'category_slug' => 'arts',
            'image' => 'https://images.unsplash.com/photo-1569783721854-33a99b4c0bae?auto=format&fit=crop&w=1600&q=80',
            'price' => 'Free',
            'ticket_url' => 'https://example.com/tickets/after-dark-gallery-circuit',
            'latitude' => -33.8868,
            'longitude' => 151.1974,
            'featured' => false,
        ],
        [
            'title' => 'Saturday Street Food Sessions',
            'slug' => 'saturday-street-food-sessions',
            'description' => 'Chefs, natural wine pop-ups and a rotating vinyl-only DJ roster.',
            'start_datetime' => '2026-08-15T12:00:00+10:00',
            'end_datetime' => '2026-08-15T21:30:00+10:00',
            'venue_slug' => 'carriageworks',
            'suburb' => 'Eveleigh',
            'category' => 'Food & Drink',
            'category_slug' => 'food-drink',
            'image' => 'https://images.unsplash.com/photo-1552912470-ee2e96439539?auto=format&fit=crop&w=1600&q=80',
            'price' => '$15+',
            'ticket_url' => 'https://example.com/tickets/saturday-street-food-sessions',
            'latitude' => -33.8953,
            'longitude' => 151.1922,
            'featured' => true,
        ],
        [
            'title' => 'Night Shift House Party',
            'slug' => 'night-shift-house-party',
            'description' => 'Two rooms, local selectors and sunrise-adjacent energy.',
            'start_datetime' => '2026-08-15T22:00:00+10:00',
            'end_datetime' => '2026-08-16T03:00:00+10:00',
            'venue_slug' => 'factory-theatre',
            'suburb' => 'Marrickville',
            'category' => 'Nightlife',
            'category_slug' => 'nightlife',
            'image' => 'https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1600&q=80',
            'price' => '$30',
            'ticket_url' => 'https://example.com/tickets/night-shift-house-party',
            'latitude' => -33.9076,
            'longitude' => 151.1625,
            'featured' => true,
        ],
        [
            'title' => 'Sunday Derby Live Site',
            'slug' => 'sunday-derby-live-site',
            'description' => 'Big screens, local brewers, and a match-day crowd in Barangaroo.',
            'start_datetime' => '2026-08-16T15:00:00+10:00',
            'end_datetime' => '2026-08-16T20:00:00+10:00',
            'venue_slug' => 'metro-theatre',
            'suburb' => 'Barangaroo',
            'category' => 'Sport',
            'category_slug' => 'sport',
            'image' => 'https://images.unsplash.com/photo-1563299796-b729d0af54a5?auto=format&fit=crop&w=1600&q=80',
            'price' => '$12',
            'ticket_url' => 'https://example.com/tickets/sunday-derby-live-site',
            'latitude' => -33.8635,
            'longitude' => 151.2013,
            'featured' => false,
        ],
        [
            'title' => 'Harbour Fringe Opening Night',
            'slug' => 'harbour-fringe-opening-night',
            'description' => 'Independent theatre premieres, installations and roaming performance.',
            'start_datetime' => '2026-08-21T18:00:00+10:00',
            'end_datetime' => '2026-08-21T23:00:00+10:00',
            'venue_slug' => 'hayes-theatre',
            'suburb' => 'Potts Point',
            'category' => 'Festivals',
            'category_slug' => 'festivals',
            'image' => 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1600&q=80',
            'price' => '$45',
            'ticket_url' => 'https://example.com/tickets/harbour-fringe-opening-night',
            'latitude' => -33.8732,
            'longitude' => 151.2230,
            'featured' => true,
        ],
        [
            'title' => 'Rooftop Jazz After Hours',
            'slug' => 'rooftop-jazz-after-hours',
            'description' => 'A late-night quartet, skyline views and relaxed Sunday momentum.',
            'start_datetime' => '2026-08-16T20:30:00+10:00',
            'end_datetime' => '2026-08-16T23:00:00+10:00',
            'venue_slug' => 'metro-theatre',
            'suburb' => 'Darlinghurst',
            'category' => 'Music',
            'category_slug' => 'music',
            'image' => 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1600&q=80',
            'price' => '$28',
            'ticket_url' => 'https://example.com/tickets/rooftop-jazz-after-hours',
            'latitude' => -33.8784,
            'longitude' => 151.2161,
            'featured' => false,
        ],
    ],

    'guides' => [
        [
            'slug' => 'what-to-do-in-sydney-this-weekend',
            'title' => 'What to do in Sydney this weekend',
            'excerpt' => 'Twelve sharp picks across gigs, comedy, theatre and after-dark food.',
        ],
        [
            'slug' => 'best-live-music-in-sydney-tonight',
            'title' => 'Best live music in Sydney tonight',
            'excerpt' => 'From Newtown rooms to city stages, where Sydney sounds best after 7pm.',
        ],
        [
            'slug' => 'whats-happening-in-newtown',
            'title' => "What's happening in Newtown",
            'excerpt' => 'A local guide to packed calendars, small stages and late dining.',
        ],
        [
            'slug' => 'sydneys-best-comedy-nights',
            'title' => "Sydney's best comedy nights",
            'excerpt' => 'Consistent open mics, showcase rooms and touring spots worth booking early.',
        ],
        [
            'slug' => 'things-to-do-after-dark',
            'title' => 'Things to do after dark',
            'excerpt' => 'A practical guide to making weekday nights in Sydney less predictable.',
        ],
        [
            'slug' => 'new-venues-worth-knowing',
            'title' => 'New venues worth knowing',
            'excerpt' => 'Fresh openings across Sydney that are already building a following.',
        ],
    ],
];
